Template: templates/nom_record.md.tpl
PrevRecord: path/to/previous_record
Number: 2
Name: 岡大 太郎
Belongs: 桃太郎研究室M2
MeetingName: 桃太郎ミーティング
RangeAutoSetFlag: True
Calendars:
  Labo:
    Ids:
      - 'calendar_id1'
      - 'calendar_id2'
      - 'calendar_id3'
  Univ:
    Ids:
      - 'calendar_id4'
    Filter:
      description: "太郎"
PrevCopy:
  Research:
    Startline: 研究関連
    Endline: 研究室関連
