Template: templates/sw_record.tex.tpl
PrevRecord: path/to/previous_record
Number: 2
Familyname: 岡大
Givenname: 太郎
FamilynameRuby: おかだい
GivennameRuby: たろう
Belongs: 桃太郎研究室M2
MeetingName: 全体ミーティング
RangeAutoSetFlag: True
Calendars:
  Labo:
    Ids:
      - 'calendar_id1'
      - 'calendar_id2'
      - 'calendar_id3'      
  Univ:
    Ids:
      - 'calendar_id4'
    Filter:
      description: "太郎"
PrevCopy:
  Research:
    Startline: 研究関連
    Endline: 研究室関連
